2021-08-26 14:19:44,943 - ERROR - test_login.py[41]:Traceback (most recent call last):
  File "E:\pythonTest\waimaiProject\test_case\test_login.py", line 39, in test_login
    assert res['msg'] == expData['msg']#断言：预期与实际相比较，一致返回真，不一致-假
AssertionError: assert '输入的密码错误!' == '成功'
  - 成功
  + 输入的密码错误!

